name: CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.13.0'
    - name: npm install, build and test
      run: |
        npm install
        npm run build --prod
        npm test
